# Generated by Django 5.0 on 2024-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
